version: "3.8"
services:
  cache:
    image: "redis:latest"
    expose:
      - "6379"
  api:
    build: .
    environment: -"RAILS_ENV=development"
    ports:
      - "80:3000"
    volumes:
      - .:/app
    depends_on:
      - "cache"
