version: "3.8"
services:
  cache:
    image: "redis:latest"
    expose:
      - "6379"
  api:
    build: .
    environment:
      - "RAILS_ENV=production"
      - "PRODUCTION_HOST=${PRODUCTION_HOST}"
      - "PRODUCTION_CLIENT_ORIGIN=${PRODUCTION_CLIENT_ORIGIN}"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - "cache"
