version: "3.8"
services:
  cache:
    image: "redis:latest"
    expose:
      - "6379"
  api:
    build: .
    environment:
      - "RAILS_ENV=development"
      - "SCRAPE_URL=${SCRAPE_URL}"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - "cache"
