version: "3.8"
services:
  cache:
    image: "redis:latest"
    expose:
      - "6379"
  api:
    build: .
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "80:3000"
    command:
      - ./run.sh
    depends_on:
      - "cache"
